language: generic
os: osx
matrix:
  include:
    - os: linux
      script: make
      env: COMPILER_NAME=g++-6 CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - nasm
            - uuid-dev
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      script: make MALLOC=libc
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8 CXXFLAGS="-stdlib=libc++" LDFLAGS="-stdlib=libc++"
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - nasm
            - uuid-dev
          sources: *sources
